# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtY-naV5o_lKd523RDbwPuNQZjZlizJS
"""

from openai import OpenAI

client = OpenAI(
    base_url=f"{endpoint}",
    api_key=api_key
)

pip install openai

import sys
print (sys.executable)

pip install openai

from openai import OpenAI

endpoint = "https://15pri02460-0036-resource.services.ai.azure.com/openai/v1/"
model_name = "Phi-4-reasoning"
deployment_name = "Phi-4-reasoning"

api_key = "<Yur api key>"

client = OpenAI(
    base_url=f"{endpoint}",
    api_key=api_key
)

completion = client.chat.completions.create(
    model=deployment_name,
    messages=[
        {
            "role": "user",
            "content": "What is the capital of France?",
        }
    ],
)

print(completion.choices[0].message)